### ISSUE TITLE
Could you please add an option to make space before colon `:`

### ISSUE THREAD

**Issue by Scvairy** [tillig/json-sort-cli#28]
I want to add a pre-commit hook to sort Contents.json files generated for Xcode (or by xcode), and in its flavor of json there is a space before colon.
To reduce diff, I'd like to follow xcode's rules, but I don't know if it is possible...

**Comment by tillig** [comment]
Unfortunately, [`json-stable-stringify` doesn't support additional formatting options](https://www.npmjs.com/package/json-stable-stringify). The wrapper I have here is specifically to use that library, so you'd need to get them to support it before I would be able to. Sorry.
