### ISSUE TITLE
Command line option `--insert-final-new-line` doesn't seem to have an effect

### ISSUE THREAD

**Issue by dmohns** [tillig/json-sort-cli#40]
Running 

```sh
json-sort --indent-size 4 --insert-final-new-line true test.json
```

doesn't complain about missing new line at the end of `test.json`. Similarly the `--autofix` option doesn't add it.

```sh
> json-sort --version

1.1.1
```

**Comment by tillig** [comment]
Looks like you might have a typo in your command line there - it's `--insert-final-newline` (`newline` is one word) not `--insert-final-new-line`. If I run it with the correct flag, it seems to work. I also verified I have it properly spelled in the README.

Can you double-check whether the `--insert-final-newline` works?

**Comment by dmohns** [comment]
🤦 Haha, sorry! That does the trick. Thanks for the quick help!

Maybe some future improvement idea could be to fail the cli if user passes wrong argument. But not sure how complicated this is to implement, and certainly not the most important feature.
