### ISSUE TITLE
[Question] How to use a custom compare function?

### ISSUE THREAD

**Issue by george-gca** [tillig/json-sort-cli#89]
How can I give a [custom compare function](https://github.com/ljharb/json-stable-stringify?tab=readme-ov-file#cmp) to be used by the `json-stable-stringify` algorithm in a pre commit hook?

**Comment by tillig** [comment]
Short answer: you can't. This is primarily a command line tool, and then, primarily created for use in [pre-commit hook support](https://pre-commit.com/). Passing options that aren't easily managed or serializable on a command line isn't something I'm looking to support. Adding `eval` makes it a security problem, so passing function-as-text is also not an option. Sorry.
